version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL="http://es01:9200/"
      - ELASTICSEARCH_HOSTS="http://es01:9200"
      - SERVER_BASEPATH="/kibana"
    ports:
      - 5601:5601
    networks:
      - elastic

#  logstash:
#    image: docker.elastic.co/logstash/logstash:7.17.0
#    container_name: logstash
#    volumes:
#     - "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
#    ports:
#      - 5044:5044
#    networks:
#      - elastic
#    depends_on:
#      - es01

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
